### ISSUE TITLE
Do you already have a free USB ID registered for your device (For porting Circuitpython to it)

### ISSUE THREAD

**Issue by expandme-tech** [eggsampler/ESP32-S2-Breakout#2]
https://github.com/adafruit/circuitpython/issues/3414#issuecomment-724896324

https://github.com/skieast/circuitpython/tree/main-copy/ports/esp32s2/boards

Rudolf

**Comment by eggsampler** [comment]
This is not something I plan on doing as it is just a one-off general purpose dev board and not a specific project, sorry.
