### ISSUE TITLE
Was the test of the crystal successful?

### ISSUE THREAD

**Issue by MangoIV** [eggsampler/ESP32-S2-Breakout#3]
Hi! I'm currently trying to design a PCB using the esp32-s2 wroom and am wondering whether you already have a reference on which passives work with the oscillator. I'm especially interested in the values of the 3 resistors.
Thanks in advance.

**Comment by eggsampler** [comment]
Hi,

I ended up using no resistors apart from a zero ohm on the series one. With standard crystal resistors there didn't seem to be any real need to limit the drive current or have these resistors at all.

Happy to be proven wrong, but it worked fine without it.
