### ISSUE TITLE
Most compatible board definition in Arduino?

### ISSUE THREAD

**Issue by john--** [eggsampler/ESP32-S2-Breakout#6]
Hi there,

Board works great. Thanks so much for this. I was just curious if you use Arduino for flashing sketches, and if so, which definition do you use? "Adafruit Feather ESP32-S2 (no PSRAM)" seems to work, but I've been struggling to get i2c working on pins 8/9 (even with the appropriate pull-ups), and can't really figure out what I could be doing wrong.

**Comment by eggsampler** [comment]
Hi,

I tend to use PlatformIO, but if you use the latest development version of the esp32-arduino and use the "ESP32S2 Dev Module" board, that should be the most compatible.
